apiVersion: v1
kind: Namespace
metadata:
  name: mongo
---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: mongo
  name: mongo-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  hostPath:
    path: "/YourPath/demo/vol/mongo"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: mongo
  name: mongo-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: mongo
  name: mongo-dns
data:
  upstreamNameservers: |
    ["8.8.8.8"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: mongo
  name: mongo-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-api
  template:
    metadata:
      labels:
        app: mongo-api
    spec:
      # need to setup DNS policy or an error "bad auth : Authentication failed." shows up
      dnsPolicy: Default
      volumes:
      - name: mongo-app
        persistentVolumeClaim:
          claimName: mongo-pvc
      containers:
      - name: mongo-api
        image: mongo-api
        imagePullPolicy: Never
        ports:
        - containerPort: 8600
          name: mongo-api
        volumeMounts:
        - name: mongo-app
          mountPath: "/tmp/"
---
apiVersion: v1
kind: Service
metadata:
  namespace: mongo
  name: mongo-service
spec:
  type: LoadBalancer
  selector:
    app: mongo-api
  # get it by: hostname -I | awk '{print $1}'
  externalIPs:
    - xxx.xxx.xxx.xxx
  ports:
    - port: 8600
      targetPort: 8600
#   OR fixed the node port      
#   ports:
#     - name: http
#       port: 8600
#       nodePort: 31600
